# Generated by Django 4.1.7 on 2023-02-24 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('developer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('developer_name', models.CharField(max_length=50)),
                ('developer_fdate', models.CharField(max_length=10)),
                ('developer_adress', models.TextField(blank=True, default='Blank adress')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=50)),
                ('game_rating', models.IntegerField()),
                ('game_desc', models.TextField(blank=True, default='Blank Description')),
                ('game_rdate', models.CharField(max_length=10)),
                ('game_cover', models.ImageField(default='default_cover.jpg', upload_to='game_covers')),
                ('game_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('game_dev', models.ManyToManyField(to='api.developer')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=50)),
                ('player_jdate', models.CharField(max_length=10)),
                ('player_bdate', models.CharField(max_length=10)),
                ('player_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gender')),
                ('player_owngames', models.ManyToManyField(blank=True, to='api.games')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=50)),
                ('publisher_fdate', models.CharField(max_length=10)),
                ('publisher_adress', models.TextField(blank=True, default='Blank adress')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_owner', models.CharField(max_length=50)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sale_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.CharField(max_length=10)),
                ('sale_paytype', models.CharField(max_length=15)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('sale_soldgames', models.ManyToManyField(to='api.games')),
                ('sale_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.wallet'),
        ),
        migrations.AddField(
            model_name='games',
            name='game_glist',
            field=models.ManyToManyField(to='api.genres'),
        ),
        migrations.AddField(
            model_name='games',
            name='game_pub',
            field=models.ManyToManyField(to='api.publisher'),
        ),
    ]
