# Generated by Django 4.1.7 on 2023-02-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paytype_alter_sales_sale_paytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytype',
            name='paytype_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
